export const assetKeys = {
  player: 'character:starter-child-south',
  playerSouth: 'character:starter-child-south',
  playerNorth: 'character:starter-child-north',
  playerEast: 'character:starter-child-east',
  playerWest: 'character:starter-child-west',
  playerSouthEast: 'character:starter-child-south-east',
  playerSouthWest: 'character:starter-child-south-west',
  playerNorthEast: 'character:starter-child-north-east',
  playerNorthWest: 'character:starter-child-north-west',
  playerHeldBranchClub: 'character:held-branch-club',
  playerHeldStoneEdge: 'character:held-stone-edge',
  enemy: 'character:hollow-wolf',
  wolfIdleWatch: 'character:wolf-idle-watch',
  grassBase: 'environment:grass-base',
  dirtClearing: 'environment:dirt-clearing',
  grassClearingEdge: 'environment:grass-clearing-edge',
  darkUndergrowth: 'environment:dark-undergrowth',
  resourceHerb: 'environment:resource-herb',
  resourceStone: 'environment:resource-stone',
  resourceWood: 'environment:resource-wood',
  resourceFruit: 'environment:resource-fruit',
  resourceTwigs: 'environment:resource-twigs',
  resourceDryGrass: 'environment:resource-dry-grass',
  resourceBark: 'environment:resource-bark',
  resourceStrikingStone: 'environment:resource-striking-stone',
  grass: 'environment:cel-grass',
  campfire: 'environment:campfire',
  campfireDead: 'environment:campfire-dead',
  campfireLit: 'environment:campfire-lit',
  deadFirePit: 'environment:dead-fire-pit',
  litFirePit: 'environment:lit-fire-pit',
  leafBed: 'environment:leaf-bed',
  treeCluster: 'environment:tree-cluster',
  treeClusterAlt: 'environment:tree-cluster-alt',
  zone1TreeTrunk: 'environment:zone1-tree-trunk',
  zone1TreeRoots: 'environment:zone1-tree-roots',
  zone1TreeTrunkBody: 'environment:zone1-tree-trunk-body',
  zone1TreeCanopy: 'environment:zone1-tree-canopy',
  roundBush: 'environment:round-bush',
  grassClump: 'environment:grass-clump',
  smallTree: 'environment:small-tree',
  sleepingSpot: 'environment:sleeping-spot',
  fallenBranch: 'environment:fallen-branch',
  tornCloth: 'environment:torn-cloth',
  ashMark: 'environment:ash-mark',
  gatherPatch: 'environment:gather-patch',
  trailStone: 'environment:trail-stone',
  flower: 'environment:spirit-flower',
  shadow: 'fx:soft-shadow'
} as const;

export const animationKeys = {
  wolfIdleWatch: 'anim:wolf-idle-watch'
} as const;
